# Generated by Django 6.0.5 on 2026-05-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='bi-building', help_text='Clase de Bootstrap Icons', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Espacio',
                'verbose_name_plural': 'Tipos de Espacios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: AULA-101, LAB-205', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(help_text='Ej: Bloque A, Piso 2', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('equipamiento', models.TextField(blank=True, help_text='Recursos Disponibles')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('inactivo', 'Inactivo')], default='disponible', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='espacios/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacios', to='espacios.tipoespacio')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
